# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import stdimage.models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('1', 'Ingenier\xeda Inform\xe1tica'), ('2', 'Ingenier\xeda en Sistemas Computacionales'), ('3', 'Ingenier\xeda Electromecanica'), ('4', 'Ingenier\xeda Industrial')], max_length=100)),
                ('matricula', models.CharField(max_length=9)),
                ('pic', stdimage.models.StdImageField(blank=True, default='default.png', upload_to=users.models.upload_location)),
                ('semestre', models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Septimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Residencias')], max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
