# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='degree',
            field=models.CharField(choices=[('1', 'Ingenier\xeda Inform\xe1tica'), ('2', 'Ingenier\xeda en Sistemas Computacionales'), ('3', 'Ingenier\xeda Electromecanica'), ('4', 'Ingenier\xeda Industrial')], max_length=100),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='semestre',
            field=models.CharField(choices=[('1', 'Primero'), ('2', 'Segundo'), ('3', 'Tercero'), ('4', 'Cuarto'), ('5', 'Quinto'), ('6', 'Sexto'), ('7', 'Septimo'), ('8', 'Octavo'), ('9', 'Noveno'), ('10', 'Residencias')], max_length=100),
        ),
    ]
