# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 04:17
from __future__ import unicode_literals

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default='default.png', upload_to=users.models.upload_location),
        ),
    ]
