# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170417_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Degree', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Semestre', verbose_name='Semestre'),
        ),
    ]
