# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 21:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20170416_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='comments.Comment'),
        ),
    ]
